### ISSUE TITLE
wrong number of arguments (3 for 2)

### ISSUE THREAD

**Issue by alexmobo** [weppos/tabs_on_rails#25]
Here is my problem.

I've only one controller to navigate throught my primary tab menu...

> class StaticPagesController < ApplicationController
>  def home
>    set_tab :home
>  end
> ...
>  def facilities
>    set_tab :facilities
>    @facilities = Facility.all
> 
>    set_tab :second, :navigation, :only => %w(second)
>    set_tab :third, :navigation, :only => %w(third)
>    set_tab :first, :navigation, :only => %w(first)
>  end
> 
>  def first; end
>  def second; end
>  def third; end
> ...
>  def contact
>    set_tab :contact
>  end
> end

and I want to create a sub-menu inside facilities static page.

When I try to run this code, rails throws me the error:

> wrong number of arguments (3 for 2)

on line:

> set_tab :second, :navigation, :only => %w(second)

It seems that isn't finding the method:

> set_tab(*args)

Thanks in advanced,
Alex

**Comment by weppos** [comment]
Closing as very old. Feel free to reopen if still applicable.
