### ISSUE TITLE
Shall we create dynamic tabs through view.

### ISSUE THREAD

**Issue by shivareddy547** [weppos/tabs_on_rails#36]
Hi,

Shall we create dynamic menus like Tabs (Management) creation,Footer links management using tabs_on_rails gem.

As per my requirement i need to manage tabs through admin configuration.

Thanks in advance.

Thanks
Shiva.A

**Comment by weppos** [comment]
The library handles the storage and generation of tabs at Ruby level. How you generate the tabs is irrelevant. Hence, technically, you can use the plugin for your scope.
